version: '3.7'
services:
  gitlab:
    restart: always
    image: 'gitlab/gitlab-ee:13.8.2-ee.0'
    container_name: gitlab
    hostname: gitlab
    networks:
      - gitlab-network
    volumes:
      - './config:/etc/gitlab'
      - './data:/var/opt/gitlab'
      - './logs:/var/log/gitlab'
    ports:
      - '2222:22'
      - '4000:80'
      - '4443:443'
      - '4001:4001'
      - '9090:9090'

  gitlab-runner:
    restart: always
    image: 'gitlab/gitlab-runner:latest'
    container_name: gitlab-runner
    hostname: gitlab-runner
    networks:
      - gitlab-network
    volumes:
      - './runner-config:/etc/gitlab-runner:Z'
      - '/var/run/docker.sock:/var/run/docker.sock'

networks:
  gitlab-network:
